#!/usr/bin/env bash
set -euo pipefail

row() {
    printf '  %-24s %-14s %-18s %s\n' "$1" "$2" "$3" "$4"
}

section() {
    printf '\n%s\n' "$1"
    printf '  %-24s %-14s %-18s %s\n' 'TARGET' 'CLASS' 'INPUT' 'DESCRIPTION'
    printf '  %-24s %-14s %-18s %s\n' '------------------------' '--------------' '------------------' '-----------'
}

printf 'PixSeal available test/check targets\n'
printf 'Legend: INPUT=pics means the local qualification corpus; private means files are never shipped.\n'
printf 'Research/qualification targets may intentionally fail at current robustness boundaries; release-check is the production gate.\n'

section 'Release / baseline'
row toolchain-check RELEASE source 'qualified Go 1.25.1 toolchain guard'
row version-check RELEASE self 'VERSION/buildinfo consistency'
row vet RELEASE source 'go vet on all packages'
row release-unit RELEASE source 'release-scoped Go unit/regression gate'
row v4-build44-jpeg-compat-test RELEASE source 'Build44 deterministic pre-Go-1.26 JPEG raster contract + CLI ingest regression'
row v3-freeze-check RELEASE source 'verify frozen v3 core SHA-256 manifest'
row v4-pilot-lock-check FORMAT source 'Build30 semantic lock for prototype-2 mask/sign identity'
row corpus-manifest-check RELEASE pics 'Build32 exact active-corpus names, dimensions and SHA-256'
row test-images RELEASE pics 'authenticated round-trip on each image/profile'
row deep-test QUALIFICATION pics 'strict baseline JPEG/resize/crop suite; corpus-sensitive'
row core-target-check PORTABILITY source 'compile reusable core for Linux/Windows/Android/iOS'
row release-check AGGREGATE source+pics 'complete production release baseline gate'

section 'Research / diagnostics'
row research-unit RESEARCH source 'experimental geometry Go regressions'
row lattice-estimator-test RESEARCH source 'local lattice estimator regressions'
row homography-test RESEARCH source 'bounded homography/projective regressions'
row photometric-test RESEARCH source 'bounded photometric bank regressions'
row bit-channel-test RESEARCH source 'protected-bit/ECC diagnostics'
row reliability-test RESEARCH source 'soft Hamming/full-grid regressions'
row spatial-channel-test RESEARCH source 'spatial coded-bit stability regressions'
row phase-surface-test RESEARCH source 'confidence-weighted phase surface regressions'
row blind-phase-test RESEARCH source 'repetition + cross-cell blind phase regressions'
row lattice-phase-test RESEARCH source 'local fractional lattice-phase regressions'
row global-unwrap-test RESEARCH source 'exact global +/-1 unwrap + exact top-2/split-repetition/rollback regressions'
row crossfit-unwrap-test RESEARCH source 'disjoint coded-bit-group proposal/validation cross-fit regressions'
row stability-unwrap-test RESEARCH source '8-partition/16-trial integer-cycle field stability regressions'
row cycle-anchor-test RESEARCH source 'unguided cross-cell image-domain cycle-anchor regressions'
row observability-audit-test RESEARCH source 'static key-independent Format-v3 cycle observability audit'
row physical-topology-test RESEARCH source 'held-out image-domain repetition-topology observability probe'
row v4-design-study-test RESEARCH source 'non-normative absolute-pilot Format-v4 sizing/design study'
row v4-foundation-test RESEARCH source 'isolated build23 provisional v4 pilot/data-plane invariants'
row v4-pilot-search-test RESEARCH source 'Build24 reproducible joint pilot search + partial-visibility qualification'
row v4-pilot-channel-test RESEARCH source 'Build24 pilot-only synthetic image-channel qualification'
row v4-pilot-corpus-test RESEARCH pics 'Build24 pilot-only qualification on local original images'
row v4-pilot-geometry-test RESEARCH source 'Build25 known-geometry rotation/affine/perspective pilot qualification'
row v4-pilot-geometry-corpus-test RESEARCH pics 'Build25 known-geometry pilot qualification on local originals'
row v4-pilot-blind-geometry-test RESEARCH source 'Build26 bounded blind geometry via repeat proposal + pilot validation'
row v4-pilot-blind-geometry-corpus-test RESEARCH pics 'Build26 blind pilot-assisted geometry on local originals'
row v4-pilot-placement-test RESEARCH source 'Build27 unknown crop/translation/placement with independently supplied geometry'
row v4-pilot-placement-corpus-test RESEARCH pics 'Build27 unknown-placement qualification on local originals'
row v4-pilot-joint-affine-test RESEARCH source 'Build28 joint blind rotation+anisotropic-scale plus unknown crop/translation'
row v4-pilot-joint-affine-corpus-test RESEARCH pics 'Build28 joint blind affine+crop qualification on local originals'
row v4-pilot-joint-projective-test RESEARCH source 'Build29 bounded joint projective+crop and affine+padded qualification; includes explicit acceptance gates'
row v4-pilot-joint-projective-corpus-test RESEARCH pics 'Build29 local originals: qualified ACCEPT cases plus explicit SAFE REJECT cases'
row v4-pilot-joint-projective-rank-diagnostic RESEARCH pics 'Build33 MQ truth-basin ranks across structural/half-pilot/full-proposal stages on random and authenticated-v4 data planes'
row v4-build34-projective-frame-corpus-test RESEARCH pics 'Build34 blind MQ projective geometry followed by exact CRC/HMAC-authenticated v4 payload recovery'
row v4-build35-projective-api-test RESEARCH source 'Build35 exported blind-projective v4 API/CLI + canonical-dimension contract'
row v4-build36-soft-channel-test RESEARCH source 'Build36 post-geometry soft Hamming physical-channel decoder'
row v4-build37-scanner-registration-test RESEARCH source 'Build37 blind paper-boundary + split-pilot scanner registration and ensemble decode'
row v4-build38-phone-channel-test RESEARCH source 'Build38 strength-48 smartphone qualification carrier round-trip/JPEG gate'
row v4-build39-phone-registration-test RESEARCH source 'Build39 bounded phone downsample + perspective boundary + spatially split public-pilot registration checkpoint'
row v4-build40-phone-residual-test RESEARCH source 'Build40 bounded smooth phone residual field fitted on proposal pilot tiles and accepted only by held-out pilot validation'
row v4-build41-phone-basin-test RESEARCH source 'Build41 fixed-holdout proposal-only phone basin search, frozen geometry shortlist, diverse two-hypothesis ensemble and authenticated synthetic recovery'
row v4-build42-phone-data-test RESEARCH source 'Build42 post-geometry qualified-bank triples plus bounded ML Hamming list decoding; HMAC remains final verifier'
row v4-build43-phone-side-pair-test RESEARCH source 'Build43 proposal-only side-pair fallback; frozen bank precedes held-out qualification'
row v4-build43-phone-physical-test PRIVATE private/v4-phone 'Build43 gate: controls reject; A/front+A/mild+A/angle+B/front authenticate; B/mild+B/angle informational'
row v4-pilot-lock-corpus-test RESEARCH pics 'Build30 known-mapping corpus evidence for the locked pilot candidate'
row v4-frame-test FORMAT source 'Build31 experimental v4 frame/ECC/HMAC/data mapping + CLI round-trip'
row v4-frame-corpus-test RESEARCH pics 'Build31 real-image v4 frame round-trip, JPEG-q82 and aligned crop'
row smooth-phase-test RESEARCH source 'bounded smooth phase-field regressions'
row geometry-test RESEARCH pics 'strict rotation/combined geometry suite; corpus-sensitive'
row affine-test RESEARCH pics 'strict axis-aligned affine suite; corpus-sensitive'
row composition-test RESEARCH pics 'strict anisotropic-scale + rotation suite; corpus-sensitive'
row lattice-test RESEARCH pics 'strict direct lattice-basis composition suite; corpus-sensitive'
row perspective-test RESEARCH pics 'strict mild projective perspective suite; corpus-sensitive'

section 'Private physical-channel'
row v4-physical-fixtures PRIVATE pics 'generate Build35 scanner-first MQ control + two authenticated v4 print carriers'
row v4-physical-qualification PRIVATE private/v4-physical 'HMAC-qualify Build35 captures with the generic projective decoder'
row v4-phone-fixtures PRIVATE pics 'generate Build38 MQ control + two strength-48 smartphone print carriers'
row v4-build40-phone-corpus-diagnostic PRIVATE private/v4-phone 'run all nine strength-48 phone captures and write stage-by-stage TSV/Markdown telemetry; does not alter decoder decisions'
row v4-build41-phone-physical-test PRIVATE private/v4-phone 'Build41 staged physical gate: all three controls reject and at least one A plus one B capture authenticate exactly'
row v4-build42-phone-physical-test PRIVATE private/v4-phone 'Build42 gate: controls reject, A/angle+B/front stay direct PASS, and A/mild authenticates via data-list fallback'
row v4-build44-phone-physical-test PRIVATE private/v4-phone 'qualified Build44 physical gate on Go 1.26 with deterministic JPEG ingest'
row v4-build37-physical-scanner-test PRIVATE private/v4-physical 'blind full-page scanner control/A/B HMAC qualification'
row print-camera-test PRIVATE private/print-camera 'print -> paper -> smartphone; PASS requires Format-v3 HMAC'
row print-scan-test PRIVATE private/print-scan 'print -> scanner; PASS requires Format-v3 HMAC'

section 'Exploratory / compatibility'
row extreme-test QUALIFICATION pics 'progressive resize/crop limit map; non-strict by design'
row v4-build44-go126-jpeg-compat-test COMPATIBILITY source 'explicit Go 1.26 deterministic JPEG qualification regression'
row test-unit COMPATIBILITY source 'complete go test ./... suite'
row test AGGREGATE source+pics 'build + test-unit + image round-trips'
row all AGGREGATE source+pics 'test + baseline transformation suite'
row all-test AGGREGATE source+pics '63-target Build44 baseline matrix; Go 1.26 physical promotion remains opt-in'

printf '\nTip: use make <target>. For all-test, optionally set ALL_TEST_REPORT=path/to/report.txt.\n'
